easy_admin_bundle:
    resource: "@AppAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /

admin_dashboard:
    defaults: { _controller: AppAdminBundle:Admin:dashboard }
    pattern:  /dashboard/

change_part:
    defaults: { _controller: AppAdminBundle:Admin:changePart }
    pattern:  /change_part/